_DEFINE: ("визначити" | "define") _SPACE?
_CALL: ("викликати" | "виклик" | "call") _SPACE?
_WITH: ("з" | "with") _SPACE?
_DEF: ("функція" | "зах" | "def") _SPACE?
_RETURN: ("повернути" | "return") _SPACE?
_PRINT: ("надрукувати" | "друкуй" | "print") _SPACE?
_PLAY: ("грати" | "play") _SPACE
_ASK: ("запитати" | "запитай" | "ask")
_ECHO: ("ехо" | "echo") _SPACE?
_FORWARD: ("вперед" | "forward") _SPACE?
_TURN: ("поверни" | "turn") _SPACE?
left: ("вліво" | "left") _SPACE?
right: ("вправо" | "right") _SPACE?
black: ("чорний" | "black") _SPACE?
blue: ("синій" | "blue") _SPACE?
brown: ("коричневий" | "brown") _SPACE?
gray: ("сірий" | "gray") _SPACE?
green: ("зелений" | "green") _SPACE?
orange: ("оранжевий" | "orange") _SPACE?
pink: ("рожевий" | "pink") _SPACE?
purple: ("фіолетовий" | "purple") _SPACE?
red: ("червоний" | "red") _SPACE?
white: ("білий" | "white") _SPACE?
yellow: ("жовтий" | "yellow") _SPACE?
_IS: _SPACE ("чи" | "це" | "is") _SPACE
_STANDALONE_IS: ("чи" | "це" | "is")
_SLEEP: ("почекати" | "почекай" | "sleep") _SPACE?
_ADD_LIST: ("додати" | "додай" | "add") _SPACE
_TO_LIST: _SPACE? ("до" | "to")
_REMOVE: ("вилучити" | "видали" | "remove") _SPACE
_FROM: _SPACE? ("із" | "iз" | "з" | "from")
_AT: _SPACE ("обрати" | "на позиції" | "at") _SPACE
random: ("навмання" | "випадковий" | "випадковій" | "random") _SPACE?
_IN: _SPACE ("в" | "in") _SPACE
_NOT_IN: _SPACE ("не в" | "not in") _SPACE
_IF: ("якщо" | "if") _SPACE
_ELSE: "інакше" | "else"
_AND: _SPACE? ("і" | "and") _SPACE
_REPEAT: ("повторити" | "повтори" | "repeat") _SPACE
_TIMES: _SPACE ("разів" | "рази" | "раз" | "times")
_FOR: ("для" | "for") _SPACE
_RANGE: ("діапазоні" | "діапазон" | "діапазонi" | "range") _SPACE?
_TO: _SPACE ("до" | "to") _SPACE
_STEP: "крок" | "step"
_ELIF: _SPACE? ("інакше якщо" | "elif") _SPACE
_INPUT: ("ввести" | "введи" | "input")
_OR: _SPACE? ("або" | "or") _SPACE
_WHILE: ("тоді як" | "while") _SPACE
_LENGTH: "довжина" | "length"
_COLOR : ("колір" | "color") _SPACE?
_PRESSED: ("натиснута" | "натиснув" | "pressed") _SPACE?
clear: ("очистити" | "clear") _SPACE?
TRUE: ("true" | "True" | "true" | "True") _SPACE?
FALSE: ("false" | "False" | "false" | "False") _SPACE?
